media:
  input: assets
  output: assets

content:
  - name: Tracks
    label: Your Music Library
    type: file
    path: tracks.json
    format: json
    list: true
    fields:
      - name: title
        type: string
        label: Song Title
        required: true
      - name: ep
        type: string
        label: EP / Album Name
        required: true
      - name: releaseDate
        type: string
        label: Release Date (YYYY-MM-DD)
        required: true
      - name: src
        type: file
        label: Streaming Audio File (MP3)
        required: true
      - name: mp3
        type: file
        label: Download MP3 File (Compressed)
        required: true
      - name: wav
        type: file
        label: Download WAV File (High-Quality Raw)
        required: true
      - name: cover
        type: file
        label: EP / Album Cover Art
        required: true